# Generated by Django 6.0 on 2026-08-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_adr0001_lesson_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='options_en',
            field=models.JSONField(blank=True, default=list, help_text='Answer options in English, same order'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='options_ru',
            field=models.JSONField(blank=True, default=list, help_text='Answer options in Russian, same order'),
        ),
    ]
