# Generated by Django 5.2.17 on 2026-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challengequestion_options_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengequestion',
            name='explanation_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='explanation_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Why this answer is correct (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='challengequestion',
            name='time_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Working time for this one question, in seconds. Sized to the question: a calculation needs more than a name.'),
        ),
    ]
