"""
Seed the ChallengeQuestion pool.
Usage:  python manage.py seed_challenges

Every question carries the Uzbek original plus English and Russian, for the
question and for the answer options alike — `correct_answer` indexes into all
three option lists, so they must be the same list in three languages.

Safe to re-run: rows are matched on the Uzbek question text and updated in
place. A text that has been retired is switched off rather than deleted, so a
finished quiz that referenced it still resolves.
"""
from django.core.management.base import BaseCommand, CommandError

from apps.challenges.models import ChallengeQuestion

# Uzbek texts that earlier versions of this file seeded and later corrected.
RETIRED = [
    'Neytrino yulduzi nima?',  # a neutrino star is not a thing; see the neutron star question
]


def q(category, difficulty, uz, en, ru, options_uz, options_en, options_ru, correct):
    return dict(
        category=category, difficulty=difficulty,
        question=uz, question_en=en, question_ru=ru,
        options=options_uz, options_en=options_en, options_ru=options_ru,
        correct_answer=correct,
    )


QUESTIONS = [
    # ── General Space (beginner) ──
    q('general', 'easy',
      "Qaysi sayyora Qizil sayyora deb ataladi?",
      "Which planet is known as the Red Planet?",
      "Какую планету называют Красной планетой?",
      ["Venera", "Mars", "Yupiter", "Saturn"],
      ["Venus", "Mars", "Jupiter", "Saturn"],
      ["Венера", "Марс", "Юпитер", "Сатурн"], 1),
    q('general', 'easy',
      "Yerga eng yaqin yulduz qaysi?",
      "What is the closest star to Earth?",
      "Какая звезда ближе всего к Земле?",
      ["Sirius", "Alfa Sentavr", "Quyosh", "Betelgeyze"],
      ["Sirius", "Alpha Centauri", "The Sun", "Betelgeuse"],
      ["Сириус", "Альфа Центавра", "Солнце", "Бетельгейзе"], 2),
    q('general', 'easy',
      "Quyosh tizimidagi eng katta sayyora qaysi?",
      "Which planet is the largest in our solar system?",
      "Какая планета Солнечной системы самая большая?",
      ["Yer", "Saturn", "Yupiter", "Neptun"],
      ["Earth", "Saturn", "Jupiter", "Neptune"],
      ["Земля", "Сатурн", "Юпитер", "Нептун"], 2),
    q('general', 'easy',
      "Yerning nechta tabiiy yo'ldoshi bor?",
      "How many moons does Earth have?",
      "Сколько естественных спутников у Земли?",
      ["0", "1", "2", "3"], ["0", "1", "2", "3"], ["0", "1", "2", "3"], 1),
    q('general', 'easy',
      "Kosmosdan kelib Yerga tushgan toshni nima deyiladi?",
      "What do we call a rock from space that hits Earth?",
      "Как называется камень из космоса, упавший на Землю?",
      ["Meteor", "Meteorit", "Asteroid", "Kometa"],
      ["Meteor", "Meteorite", "Asteroid", "Comet"],
      ["Метеор", "Метеорит", "Астероид", "Комета"], 1),

    # ── General Space (intermediate) ──
    q('general', 'medium',
      "Biz yashaydigan galaktikaning nomi nima?",
      "What is the name of the galaxy we live in?",
      "Как называется галактика, в которой мы живём?",
      ["Andromeda", "Uchburchak", "Somon yo'li", "Sombrero"],
      ["Andromeda", "Triangulum", "Milky Way", "Sombrero"],
      ["Андромеда", "Треугольник", "Млечный Путь", "Сомбреро"], 2),
    q('general', 'medium',
      "Qaysi sayyora yonboshlab aylanadi?",
      "Which planet rotates on its side?",
      "Какая планета вращается «лёжа на боку»?",
      ["Uran", "Neptun", "Saturn", "Venera"],
      ["Uranus", "Neptune", "Saturn", "Venus"],
      ["Уран", "Нептун", "Сатурн", "Венера"], 0),
    q('general', 'medium',
      "Quyosh tizimidagi eng issiq sayyora qaysi?",
      "What is the hottest planet in our solar system?",
      "Какая планета Солнечной системы самая горячая?",
      ["Merkuriy", "Venera", "Mars", "Yupiter"],
      ["Mercury", "Venus", "Mars", "Jupiter"],
      ["Меркурий", "Венера", "Марс", "Юпитер"], 1),
    q('general', 'medium',
      "Kosmosga uchgan birinchi inson kim?",
      "Who was the first human to travel into space?",
      "Кто первым из людей полетел в космос?",
      ["Nil Armstrong", "Bazz Oldrin", "Yuriy Gagarin", "Jon Glenn"],
      ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],
      ["Нил Армстронг", "Базз Олдрин", "Юрий Гагарин", "Джон Гленн"], 2),

    # ── General Space (advanced) ──
    q('general', 'hard',
      "Koinotning taxminiy yoshi qancha?",
      "What is the approximate age of the Universe?",
      "Каков примерный возраст Вселенной?",
      ["4.5 mlrd yil", "13.8 mlrd yil", "93 mlrd yil", "1 trln yil"],
      ["4.5 billion years", "13.8 billion years", "93 billion years", "1 trillion years"],
      ["4,5 млрд лет", "13,8 млрд лет", "93 млрд лет", "1 трлн лет"], 1),
    q('general', 'hard',
      "Qora tuynuk atrofidagi yorug'lik qochib qutula olmaydigan chegara nima deyiladi?",
      "What is the boundary around a black hole beyond which no light can escape?",
      "Как называется граница вокруг чёрной дыры, из-за которой не может вырваться даже свет?",
      ["Hodisalar gorizonti", "Singulyarlik", "Akkretsion disk", "Foton sferasi"],
      ["Event horizon", "Singularity", "Accretion disk", "Photon sphere"],
      ["Горизонт событий", "Сингулярность", "Аккреционный диск", "Фотонная сфера"], 0),
    q('general', 'hard',
      "Qaysi yo'ldoshda zich atmosfera bor?",
      "Which moon has a dense atmosphere?",
      "У какого спутника есть плотная атмосфера?",
      ["Yevropa", "Ganimed", "Titan", "Triton"],
      ["Europa", "Ganymede", "Titan", "Triton"],
      ["Европа", "Ганимед", "Титан", "Тритон"], 2),

    # ── Physics ──
    q('physics', 'easy',
      "Moddiy nuqta deb nimaga aytiladi?",
      "What is a material point (point mass)?",
      "Что называют материальной точкой?",
      ["O'lchamlari berilgan sharoitda e'tiborga olinmaydigan jismga", "O'ta kichik massali jismga",
       "Faqat bitta atomdan iborat jismga", "Harakatlanmaydigan jismga"],
      ["A body whose size can be neglected in the given conditions", "A body of very small mass",
       "A body made of a single atom", "A body that does not move"],
      ["Тело, размерами которого в данных условиях можно пренебречь", "Тело очень малой массы",
       "Тело, состоящее из одного атома", "Неподвижное тело"], 0),
    q('physics', 'easy',
      "Jism to'g'ri chiziq bo'ylab 5 m/s tezlik bilan harakatlanmoqda. 10 sekundda qanday masofa bosib o'tadi?",
      "A body moves in a straight line at 5 m/s. What distance does it cover in 10 seconds?",
      "Тело движется по прямой со скоростью 5 м/с. Какой путь оно пройдёт за 10 секунд?",
      ["50 m", "2 m", "15 m", "500 m"],
      ["50 m", "2 m", "15 m", "500 m"],
      ["50 м", "2 м", "15 м", "500 м"], 0),
    q('physics', 'easy',
      "Tezligi har sekundda 2 m/s ga ortib boruvchi jismning tezlanishi qancha?",
      "A body's velocity grows by 2 m/s every second. What is its acceleration?",
      "Скорость тела каждую секунду растёт на 2 м/с. Каково его ускорение?",
      ["2 m/s^2", "0 m/s^2", "4 m/s^2", "0.5 m/s^2"],
      ["2 m/s²", "0 m/s²", "4 m/s²", "0.5 m/s²"],
      ["2 м/с²", "0 м/с²", "4 м/с²", "0,5 м/с²"], 0),
    q('physics', 'medium',
      "Tezligi 4 m/s bo'lgan jism 2 m/s^2 tezlanish bilan harakatlansa, 5 sekunddan keyingi tezligi qancha?",
      "A body moving at 4 m/s accelerates at 2 m/s². What is its velocity after 5 seconds?",
      "Тело со скоростью 4 м/с движется с ускорением 2 м/с². Какова его скорость через 5 секунд?",
      ["14 m/s", "10 m/s", "6 m/s", "20 m/s"],
      ["14 m/s", "10 m/s", "6 m/s", "20 m/s"],
      ["14 м/с", "10 м/с", "6 м/с", "20 м/с"], 0),
    q('physics', 'easy',
      "Nyutonning birinchi qonuni nimani ifodalaydi?",
      "What does Newton's first law express?",
      "Что выражает первый закон Ньютона?",
      ["Inersiya qonunini", "Kuch va tezlanish bog'liqligini", "Ta'sir va aks ta'sir qonunini",
       "Butun olam tortishish qonunini"],
      ["The law of inertia", "The relation between force and acceleration",
       "The law of action and reaction", "The law of universal gravitation"],
      ["Закон инерции", "Связь силы и ускорения", "Закон действия и противодействия",
       "Закон всемирного тяготения"], 0),
    q('physics', 'easy',
      "Massasi 2 kg bo'lgan jismga 10 N kuch ta'sir qilsa, u qanday tezlanish oladi?",
      "A force of 10 N acts on a 2 kg body. What acceleration does it get?",
      "На тело массой 2 кг действует сила 10 Н. Какое ускорение оно получит?",
      ["5 m/s^2", "20 m/s^2", "0.2 m/s^2", "12 m/s^2"],
      ["5 m/s²", "20 m/s²", "0.2 m/s²", "12 m/s²"],
      ["5 м/с²", "20 м/с²", "0,2 м/с²", "12 м/с²"], 0),
    q('physics', 'medium',
      "Kosmik kemada astronavt vaznsizlik holatida bo'lsa, uning massasi va og'irligi qanday bo'ladi?",
      "An astronaut is weightless aboard a spacecraft. What happens to their mass and weight?",
      "Космонавт на корабле находится в невесомости. Что происходит с его массой и весом?",
      ["Massasi o'zgarmaydi, og'irligi nolga teng", "Ikkalasi ham nolga teng", "Massasi nolga teng",
       "Ikkalasi ham ortadi"],
      ["Mass is unchanged, weight is zero", "Both are zero", "Mass is zero", "Both increase"],
      ["Масса не меняется, вес равен нулю", "И масса, и вес равны нулю", "Масса равна нулю",
       "И масса, и вес увеличиваются"], 0),
    q('physics', 'medium',
      "Jism vertikal yuqoriga 20 m/s tezlik bilan otildi. U eng baland nuqtaga necha sekundda yetib boradi (g=10)?",
      "A body is thrown straight up at 20 m/s. How long does it take to reach the highest point (g = 10)?",
      "Тело брошено вертикально вверх со скоростью 20 м/с. Через сколько секунд оно достигнет высшей точки (g = 10)?",
      ["2 s", "1 s", "4 s", "0.5 s"],
      ["2 s", "1 s", "4 s", "0.5 s"],
      ["2 с", "1 с", "4 с", "0,5 с"], 0),
    q('physics', 'easy',
      "Potensial energiya qaysi formuladan topiladi?",
      "Which formula gives potential energy?",
      "По какой формуле находится потенциальная энергия?",
      ["mgh", "mv^2/2", "kx^2/2", "F*s"],
      ["mgh", "mv²/2", "kx²/2", "F·s"],
      ["mgh", "mv²/2", "kx²/2", "F·s"], 0),
    q('physics', 'easy',
      "Yer sirtiga yaqin joyda erkin tushish tezlanishi qanchaga teng?",
      "What is the acceleration of free fall near Earth's surface?",
      "Чему равно ускорение свободного падения у поверхности Земли?",
      ["~9.8 m/s^2", "10.5 m/s^2", "1.6 m/s^2", "11.2 km/s"],
      ["~9.8 m/s²", "10.5 m/s²", "1.6 m/s²", "11.2 km/s"],
      ["~9,8 м/с²", "10,5 м/с²", "1,6 м/с²", "11,2 км/с"], 0),
    q('physics', 'easy',
      "Ishning o'lchov birligi nima?",
      "What is the unit of work?",
      "В каких единицах измеряется работа?",
      ["Joul (J)", "Vatt (W)", "Nyuton (N)", "Paskal (Pa)"],
      ["Joule (J)", "Watt (W)", "Newton (N)", "Pascal (Pa)"],
      ["Джоуль (Дж)", "Ватт (Вт)", "Ньютон (Н)", "Паскаль (Па)"], 0),

    # ── Astronomy ──
    q('astronomy', 'easy',
      "Quyosh sistemasidagi eng katta sayyora qaysi?",
      "Which is the largest planet in the Solar System?",
      "Какая планета в Солнечной системе самая крупная?",
      ["Yupiter", "Saturn", "Yer", "Uran"],
      ["Jupiter", "Saturn", "Earth", "Uranus"],
      ["Юпитер", "Сатурн", "Земля", "Уран"], 0),
    q('astronomy', 'easy',
      "Yorug'lik yili nima?",
      "What is a light-year?",
      "Что такое световой год?",
      ["Yorug'likning bir yilda bosib o'tgan masofasi", "Vaqt o'lchov birligi",
       "Yulduzning yoshini o'lchash birligi", "Quyoshning faollik davri"],
      ["The distance light travels in one year", "A unit of time",
       "A unit for measuring a star's age", "The Sun's activity cycle"],
      ["Расстояние, которое свет проходит за год", "Единица измерения времени",
       "Единица измерения возраста звезды", "Период активности Солнца"], 0),
    q('astronomy', 'easy',
      "Galaktikamizning nomi nima?",
      "What is our galaxy called?",
      "Как называется наша галактика?",
      ["Somon yo'li", "Andromeda", "Katta Magellan buluti", "Uchburchak"],
      ["Milky Way", "Andromeda", "Large Magellanic Cloud", "Triangulum"],
      ["Млечный Путь", "Андромеда", "Большое Магелланово Облако", "Треугольник"], 0),
    q('astronomy', 'medium',
      "Koinotning kengayishini kim kashf qilgan?",
      "Who discovered the expansion of the Universe?",
      "Кто открыл расширение Вселенной?",
      ["Edvin Xabbl", "Albert Eynshteyn", "Isaak Nyuton", "Galileo Galiley"],
      ["Edwin Hubble", "Albert Einstein", "Isaac Newton", "Galileo Galilei"],
      ["Эдвин Хаббл", "Альберт Эйнштейн", "Исаак Ньютон", "Галилео Галилей"], 0),
    q('astronomy', 'hard',
      "Qora tuynuk nima?",
      "What is a black hole?",
      "Что такое чёрная дыра?",
      ["Gravitatsiyasi shunchalik kuchliki, undan yorug'lik ham qochib qutula olmaydigan obyekt",
       "Yulduzlarning paydo bo'lish joyi", "Koinotdagi bo'shliq", "O'lchami juda kichik sayyora"],
      ["An object whose gravity is so strong that not even light can escape it",
       "A place where stars are born", "An empty region of the Universe", "A very small planet"],
      ["Объект с такой сильной гравитацией, что из него не может вырваться даже свет",
       "Место рождения звёзд", "Пустота во Вселенной", "Очень маленькая планета"], 0),

    # ── Problems ──
    q('problems', 'hard',
      "Avtomobil yo'lning birinchi yarmini 60 km/soat, ikkinchi yarmini 40 km/soat tezlik bilan o'tdi. O'rtacha tezlikni toping.",
      "A car covers the first half of a road at 60 km/h and the second half at 40 km/h. Find the average speed.",
      "Автомобиль проехал первую половину пути со скоростью 60 км/ч, вторую — 40 км/ч. Найдите среднюю скорость.",
      ["48 km/soat", "50 km/soat", "52 km/soat", "45 km/soat"],
      ["48 km/h", "50 km/h", "52 km/h", "45 km/h"],
      ["48 км/ч", "50 км/ч", "52 км/ч", "45 км/ч"], 0),
    q('problems', 'medium',
      "Bikrligi 100 N/m bo'lgan prujinani 2 sm ga cho'zish uchun qancha ish bajarish kerak?",
      "How much work is needed to stretch a spring of stiffness 100 N/m by 2 cm?",
      "Какую работу нужно совершить, чтобы растянуть пружину жёсткостью 100 Н/м на 2 см?",
      ["0.02 J", "0.04 J", "2 J", "4 J"],
      ["0.02 J", "0.04 J", "2 J", "4 J"],
      ["0,02 Дж", "0,04 Дж", "2 Дж", "4 Дж"], 0),
    q('problems', 'medium',
      "Massasi 2 kg jism 10 m balandlikdan erkin tushmoqda. Kinetik energiyasi qancha (g=10)?",
      "A 2 kg body falls freely from a height of 10 m. What is its kinetic energy at the bottom (g = 10)?",
      "Тело массой 2 кг свободно падает с высоты 10 м. Какова его кинетическая энергия у земли (g = 10)?",
      ["200 J", "100 J", "50 J", "400 J"],
      ["200 J", "100 J", "50 J", "400 J"],
      ["200 Дж", "100 Дж", "50 Дж", "400 Дж"], 0),
    q('problems', 'hard',
      "20 C dagi 5 kg suvni qaynash darajasigacha isitish uchun qancha issiqlik kerak (c=4200)?",
      "How much heat is needed to bring 5 kg of water from 20 °C to the boiling point (c = 4200)?",
      "Сколько теплоты нужно, чтобы нагреть 5 кг воды от 20 °C до кипения (c = 4200)?",
      ["1.68 MJ", "2.1 MJ", "16.8 MJ", "0.84 MJ"],
      ["1.68 MJ", "2.1 MJ", "16.8 MJ", "0.84 MJ"],
      ["1,68 МДж", "2,1 МДж", "16,8 МДж", "0,84 МДж"], 0),

    # ── Courses (online learning) ──
    q('courses', 'easy',
      "Qaysi onlayn platforma dasturlash bo'yicha eng ko'p kurslarga ega?",
      "Which online platform has the most programming courses?",
      "На какой онлайн-платформе больше всего курсов по программированию?",
      ["Coursera", "Udemy", "edX", "Khan Academy"],
      ["Coursera", "Udemy", "edX", "Khan Academy"],
      ["Coursera", "Udemy", "edX", "Khan Academy"], 1),
    q('courses', 'easy',
      "MOOC qisqartmasining ma'nosi nima?",
      "What does the abbreviation MOOC stand for?",
      "Что означает аббревиатура MOOC?",
      ["Massive Open Online Course", "Modern Online Object Creation", "Multiple Online Open Classes",
       "Main Open Online Community"],
      ["Massive Open Online Course", "Modern Online Object Creation", "Multiple Online Open Classes",
       "Main Open Online Community"],
      ["Массовый открытый онлайн-курс", "Современное онлайн-создание объектов",
       "Множество открытых онлайн-занятий", "Главное открытое онлайн-сообщество"], 0),
    q('courses', 'easy',
      "Fizika bo'yicha onlayn kurslarda eng ko'p o'qitiladigan birinchi mavzu qaysi?",
      "Which topic usually comes first in online physics courses?",
      "Какая тема обычно идёт первой в онлайн-курсах по физике?",
      ["Kinematika", "Kvant mexanikasi", "Termodinamika", "Optika"],
      ["Kinematics", "Quantum mechanics", "Thermodynamics", "Optics"],
      ["Кинематика", "Квантовая механика", "Термодинамика", "Оптика"], 0),
    q('courses', 'easy',
      "Masofaviy ta'limning afzalligi nimada?",
      "What is the advantage of distance learning?",
      "В чём преимущество дистанционного обучения?",
      ["Vaqt va joyga bog'liq emasligi", "Faqat kompyuterda o'qish mumkinligi", "Bepulligi",
       "Diplom berilmasligi"],
      ["It does not depend on time and place", "You can only study on a computer", "It is free",
       "No diploma is issued"],
      ["Не зависит от времени и места", "Учиться можно только за компьютером", "Оно бесплатное",
       "Диплом не выдаётся"], 0),
    q('courses', 'medium',
      "Khan Academy qaysi universitetning talabasi tomonidan yaratilgan?",
      "A graduate of which university founded Khan Academy?",
      "Выпускник какого университета основал Khan Academy?",
      ["MIT", "Harvard", "Stanford", "Yale"],
      ["MIT", "Harvard", "Stanford", "Yale"],
      ["MIT", "Гарвард", "Стэнфорд", "Йель"], 0),
    q('courses', 'easy',
      "Python dasturlash tili qaysi yilda yaratilgan?",
      "In what year was the Python programming language created?",
      "В каком году был создан язык программирования Python?",
      ["1991", "2000", "1985", "1995"], ["1991", "2000", "1985", "1995"], ["1991", "2000", "1985", "1995"], 0),
    q('courses', 'medium',
      "NASA Space Apps Challenge nima?",
      "What is the NASA Space Apps Challenge?",
      "Что такое NASA Space Apps Challenge?",
      ["Xalqaro hackathon", "Kosmik missiya", "Kurs platformasi", "Laboratoriya dasturi"],
      ["An international hackathon", "A space mission", "A course platform", "A laboratory programme"],
      ["Международный хакатон", "Космическая миссия", "Платформа курсов", "Лабораторная программа"], 0),
    q('courses', 'easy',
      "Qaysi tashkilot kosmik ta'lim bo'yicha bepul kurslar taqdim etadi?",
      "Which organisation offers free courses on space education?",
      "Какая организация предлагает бесплатные курсы по космическому образованию?",
      ["NASA", "Apple", "Microsoft", "Samsung"],
      ["NASA", "Apple", "Microsoft", "Samsung"],
      ["NASA", "Apple", "Microsoft", "Samsung"], 0),
    q('courses', 'medium',
      "STEM qisqartmasi nimani anglatadi?",
      "What does STEM stand for?",
      "Что означает аббревиатура STEM?",
      ["Science, Technology, Engineering, Mathematics", "Space, Technology, Energy, Mathematics",
       "Science, Teaching, Education, Modules", "System, Technology, Engineering, Management"],
      ["Science, Technology, Engineering, Mathematics", "Space, Technology, Energy, Mathematics",
       "Science, Teaching, Education, Modules", "System, Technology, Engineering, Management"],
      ["Наука, технологии, инженерия, математика", "Космос, технологии, энергетика, математика",
       "Наука, преподавание, образование, модули", "Система, технологии, инженерия, менеджмент"], 0),
    q('courses', 'hard',
      "Qaysi universitet kosmik injiniring bo'yicha dunyodagi eng nufuzli dasturga ega?",
      "Which university has the world's most prestigious space engineering programme?",
      "Какой университет имеет самую престижную в мире программу по космической инженерии?",
      ["MIT", "Oxford", "Tokyo University", "Tashkent Politexnika"],
      ["MIT", "Oxford", "University of Tokyo", "Tashkent Polytechnic"],
      ["MIT", "Оксфорд", "Токийский университет", "Ташкентский политехнический"], 0),

    # ── More physics ──
    q('physics', 'easy',
      "Sanoq sistemasi nimalardan iborat?",
      "What does a frame of reference consist of?",
      "Из чего состоит система отсчёта?",
      ["Sanoq jismi, koordinatalar sistemasi va soatdan", "Faqat koordinatalar sistemasidan",
       "Jism va uning tezligidan", "Faqat soat va asboblardan"],
      ["A reference body, a coordinate system and a clock", "Only a coordinate system",
       "A body and its velocity", "Only a clock and instruments"],
      ["Из тела отсчёта, системы координат и часов", "Только из системы координат",
       "Из тела и его скорости", "Только из часов и приборов"], 0),
    q('physics', 'easy',
      "Kuch momentining o'lchov birligi qanday?",
      "What is the unit of the moment of force (torque)?",
      "В каких единицах измеряется момент силы?",
      ["N*m", "N/m", "J/s", "W"],
      ["N·m", "N/m", "J/s", "W"],
      ["Н·м", "Н/м", "Дж/с", "Вт"], 0),
    q('physics', 'easy',
      "Quvvat qanday hisoblanadi?",
      "How is power calculated?",
      "Как вычисляется мощность?",
      ["Bajarilgan ishning vaqtga nisbati", "Kuchning masofaga ko'paytmasi",
       "Massaning tezlanishga ko'paytmasi", "Energiyaning vaqtga ko'paytmasi"],
      ["Work done divided by time", "Force multiplied by distance",
       "Mass multiplied by acceleration", "Energy multiplied by time"],
      ["Совершённая работа, делённая на время", "Сила, умноженная на расстояние",
       "Масса, умноженная на ускорение", "Энергия, умноженная на время"], 0),
    q('physics', 'medium',
      "Impulsning saqlanish qonuni qachon bajariladi?",
      "When does the law of conservation of momentum hold?",
      "Когда выполняется закон сохранения импульса?",
      ["Yopiq sistemada", "Ochiq sistemada", "Faqat elastik to'qnashuvlarda",
       "Faqat inersial bo'lmagan sanoq sistemalarida"],
      ["In a closed system", "In an open system", "Only in elastic collisions",
       "Only in non-inertial frames of reference"],
      ["В замкнутой системе", "В открытой системе", "Только при упругих столкновениях",
       "Только в неинерциальных системах отсчёта"], 0),
    q('physics', 'easy',
      "Bosim nima va uning birligi qanday?",
      "What is pressure, and what is its unit?",
      "Что такое давление и в чём оно измеряется?",
      ["Yuzaga perpendikulyar kuch; Paskal (Pa)", "Jismning massasi; Kilogramm (kg)",
       "Ishning vaqtga nisbati; Vatt (W)", "Energiyaning o'zgarishi; Joul (J)"],
      ["Force per unit area, perpendicular to the surface; pascal (Pa)", "The mass of a body; kilogram (kg)",
       "Work divided by time; watt (W)", "A change in energy; joule (J)"],
      ["Сила, перпендикулярная поверхности, на единицу площади; паскаль (Па)", "Масса тела; килограмм (кг)",
       "Работа, делённая на время; ватт (Вт)", "Изменение энергии; джоуль (Дж)"], 0),
    q('physics', 'medium',
      "Kinetik energiya nimaga bog'liq?",
      "What does kinetic energy depend on?",
      "От чего зависит кинетическая энергия?",
      ["Jismning massasi va tezligiga", "Jismning massasi va balandligiga", "Faqat jismning tezligiga",
       "Jismning shakliga"],
      ["The body's mass and velocity", "The body's mass and height", "Only the body's velocity",
       "The body's shape"],
      ["От массы и скорости тела", "От массы и высоты тела", "Только от скорости тела",
       "От формы тела"], 0),
    q('physics', 'easy',
      "Tekis harakatlanayotgan jismning tezlik-vaqt grafigi qanday?",
      "What does the velocity–time graph of uniform motion look like?",
      "Как выглядит график скорости от времени при равномерном движении?",
      ["Vaqt o'qiga parallel to'g'ri chiziq", "Parabola", "Koordinata boshidan chiquvchi to'g'ri chiziq",
       "Giperbola"],
      ["A straight line parallel to the time axis", "A parabola", "A straight line through the origin",
       "A hyperbola"],
      ["Прямая, параллельная оси времени", "Парабола", "Прямая, проходящая через начало координат",
       "Гипербола"], 0),
    q('physics', 'easy',
      "Mexanik harakat nima?",
      "What is mechanical motion?",
      "Что такое механическое движение?",
      ["Jismning boshqa jismga nisbatan holat o'zgarishi", "Issiqlik harakati", "Elektromagnit hodisa",
       "Optik hodisa"],
      ["A change in the position of a body relative to other bodies", "Thermal motion",
       "An electromagnetic phenomenon", "An optical phenomenon"],
      ["Изменение положения тела относительно других тел", "Тепловое движение",
       "Электромагнитное явление", "Оптическое явление"], 0),
    q('physics', 'medium',
      "Nyutonning uchinchi qonuni qanday ta'riflanadi?",
      "How is Newton's third law stated?",
      "Как формулируется третий закон Ньютона?",
      ["Ta'sir kuchi aks ta'sir kuchiga teng va qarama-qarshi", "Jismga ta'sir etuvchi kuchlar yig'indisi nolga teng",
       "Kuch massa va tezlanish ko'paytmasiga teng", "Jismning tezligi faqat tashqi kuchlar ta'sirida o'zgaradi"],
      ["The action force is equal and opposite to the reaction force", "The sum of forces on a body is zero",
       "Force equals mass times acceleration", "A body's velocity changes only under external forces"],
      ["Сила действия равна силе противодействия и противоположна ей", "Сумма сил, действующих на тело, равна нулю",
       "Сила равна произведению массы на ускорение", "Скорость тела меняется только под действием внешних сил"], 0),

    # ── More astronomy ──
    q('astronomy', 'easy',
      "Quyoshdan tashqari Yerga eng yaqin yulduz qaysi?",
      "Which star is closest to Earth after the Sun?",
      "Какая звезда ближе всего к Земле после Солнца?",
      ["Proksima Sentavr", "Sirius", "Betelgeyze", "Vega"],
      ["Proxima Centauri", "Sirius", "Betelgeuse", "Vega"],
      ["Проксима Центавра", "Сириус", "Бетельгейзе", "Вега"], 0),
    q('astronomy', 'medium',
      "Oyning Yer atrofida aylanish davri qancha?",
      "How long does the Moon take to orbit the Earth?",
      "Каков период обращения Луны вокруг Земли?",
      ["27.3 kun", "30 kun", "24 soat", "365 kun"],
      ["27.3 days", "30 days", "24 hours", "365 days"],
      ["27,3 суток", "30 суток", "24 часа", "365 суток"], 0),
    q('astronomy', 'easy',
      "Mars sayyorasining rangi qanday?",
      "What colour is the planet Mars?",
      "Какого цвета планета Марс?",
      ["Qizil", "Ko'k", "Sariq", "Yashil"],
      ["Red", "Blue", "Yellow", "Green"],
      ["Красный", "Синий", "Жёлтый", "Зелёный"], 0),
    q('astronomy', 'medium',
      "Saturning halqalari asosan nimadan iborat?",
      "What are Saturn's rings mostly made of?",
      "Из чего в основном состоят кольца Сатурна?",
      ["Muz va tosh parchalaridan", "Gazlardan", "Suyuq metalldan", "Tuproqdan"],
      ["Pieces of ice and rock", "Gases", "Liquid metal", "Soil"],
      ["Из кусков льда и камня", "Из газов", "Из жидкого металла", "Из грунта"], 0),
    q('astronomy', 'hard',
      "Hubble teleskopi qachon kosmosga uchirilib yuborilgan?",
      "When was the Hubble telescope launched into space?",
      "Когда телескоп «Хаббл» был запущен в космос?",
      ["1990", "2000", "1985", "1995"], ["1990", "2000", "1985", "1995"], ["1990", "2000", "1985", "1995"], 0),
    q('astronomy', 'hard',
      "Neytron yulduzi nima?",
      "What is a neutron star?",
      "Что такое нейтронная звезда?",
      ["Massiv yulduzning o'ta zich qoldig'i", "Yangi tug'ilgan yulduz", "Eng kichik yulduz turi",
       "Quyosh tizimidagi asteroid"],
      ["The extremely dense remnant of a massive star", "A newborn star", "The smallest type of star",
       "An asteroid in the Solar System"],
      ["Сверхплотный остаток массивной звезды", "Новорождённая звезда", "Самый маленький тип звёзд",
       "Астероид Солнечной системы"], 0),
    q('astronomy', 'medium',
      "Jupiterning eng katta yo'ldoshi qaysi?",
      "Which is Jupiter's largest moon?",
      "Какой спутник Юпитера самый большой?",
      ["Ganimed", "Kalisto", "Io", "Yevropa"],
      ["Ganymede", "Callisto", "Io", "Europa"],
      ["Ганимед", "Каллисто", "Ио", "Европа"], 0),

    # ── More problems ──
    q('problems', 'medium',
      "Massasi 500 g bo'lgan jism 4 m/s tezlik bilan harakatlansa, uning impulsi qancha?",
      "A 500 g body moves at 4 m/s. What is its momentum?",
      "Тело массой 500 г движется со скоростью 4 м/с. Каков его импульс?",
      ["2 kg*m/s", "2000 kg*m/s", "0.125 kg*m/s", "8 kg*m/s"],
      ["2 kg·m/s", "2000 kg·m/s", "0.125 kg·m/s", "8 kg·m/s"],
      ["2 кг·м/с", "2000 кг·м/с", "0,125 кг·м/с", "8 кг·м/с"], 0),
    q('problems', 'hard',
      "Yer atrofida uchayotgan sun'iy yo'ldoshning orbital tezligi taxminan qancha?",
      "What is the approximate orbital speed of a satellite in low Earth orbit?",
      "Какова примерная орбитальная скорость спутника на низкой околоземной орбите?",
      ["7.9 km/s", "11.2 km/s", "3.4 km/s", "29.8 km/s"],
      ["7.9 km/s", "11.2 km/s", "3.4 km/s", "29.8 km/s"],
      ["7,9 км/с", "11,2 км/с", "3,4 км/с", "29,8 км/с"], 0),
    q('problems', 'medium',
      "10 kg massali jism 5 m balandlikdan tushganda qancha kinetik energiya oladi (g=10)?",
      "How much kinetic energy does a 10 kg body gain falling from 5 m (g = 10)?",
      "Какую кинетическую энергию приобретёт тело массой 10 кг, упав с высоты 5 м (g = 10)?",
      ["500 J", "50 J", "100 J", "250 J"],
      ["500 J", "50 J", "100 J", "250 J"],
      ["500 Дж", "50 Дж", "100 Дж", "250 Дж"], 0),
    q('problems', 'hard',
      "Ikkinchi kosmik tezlik (Yerdan qochish tezligi) qanchaga teng?",
      "What is the second cosmic velocity (Earth's escape velocity)?",
      "Чему равна вторая космическая скорость (скорость убегания с Земли)?",
      ["11.2 km/s", "7.9 km/s", "16.7 km/s", "29.8 km/s"],
      ["11.2 km/s", "7.9 km/s", "16.7 km/s", "29.8 km/s"],
      ["11,2 км/с", "7,9 км/с", "16,7 км/с", "29,8 км/с"], 0),
    q('problems', 'medium',
      "R=2 m radiusli aylana bo'ylab 4 m/s tezlik bilan harakatlanayotgan jismning markazga intilma tezlanishi qancha?",
      "A body moves at 4 m/s along a circle of radius R = 2 m. What is its centripetal acceleration?",
      "Тело движется со скоростью 4 м/с по окружности радиусом R = 2 м. Каково его центростремительное ускорение?",
      ["8 m/s^2", "2 m/s^2", "16 m/s^2", "4 m/s^2"],
      ["8 m/s²", "2 m/s²", "16 m/s²", "4 m/s²"],
      ["8 м/с²", "2 м/с²", "16 м/с²", "4 м/с²"], 0),
    q('problems', 'hard',
      "Massasi 60 kg bo'lgan kosmonavt Oyda qancha og'irlik kuchiga ega (g_oy=1.6 m/s^2)?",
      "What is the weight of a 60 kg cosmonaut on the Moon (g_moon = 1.6 m/s²)?",
      "Каков вес космонавта массой 60 кг на Луне (g_Луны = 1,6 м/с²)?",
      ["96 N", "600 N", "9.6 N", "588 N"],
      ["96 N", "600 N", "9.6 N", "588 N"],
      ["96 Н", "600 Н", "9,6 Н", "588 Н"], 0),
]


def check(questions):
    """Refuse to seed a list that would be wrong on screen."""
    seen = set()
    for item in questions:
        text = item['question']
        if text in seen:
            raise CommandError(f'Duplicate question text: {text!r}')
        seen.add(text)
        for field in ('question_en', 'question_ru'):
            if not item[field].strip():
                raise CommandError(f'{field} is blank for {text!r}')
        n = len(item['options'])
        for field in ('options_en', 'options_ru'):
            if len(item[field]) != n or not all(str(o).strip() for o in item[field]):
                raise CommandError(f'{field} does not line up with options for {text!r}')
        if not 0 <= item['correct_answer'] < n:
            raise CommandError(f'correct_answer out of range for {text!r}')


class Command(BaseCommand):
    help = 'Populate the ChallengeQuestion pool with quiz questions in Uzbek, English and Russian'

    def handle(self, *args, **options):
        check(QUESTIONS)
        self.stdout.write('Seeding challenge questions...')

        created_count = 0
        for item in QUESTIONS:
            _, created = ChallengeQuestion.objects.update_or_create(
                question=item['question'], defaults={**item, 'is_active': True},
            )
            if created:
                created_count += 1

        retired = ChallengeQuestion.objects.filter(question__in=RETIRED, is_active=True).update(is_active=False)

        total = ChallengeQuestion.objects.filter(is_active=True).count()
        by_cat = {}
        for row in ChallengeQuestion.objects.filter(is_active=True).values('category'):
            by_cat[row['category']] = by_cat.get(row['category'], 0) + 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created_count} new questions, updated {len(QUESTIONS) - created_count}, '
            f'retired {retired} (active pool: {total})'
        ))
        for cat, cnt in sorted(by_cat.items()):
            self.stdout.write(f'  {cat}: {cnt} questions')
