# Generated by Django 5.2.17 on 2026-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_image_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='currency',
            field=models.CharField(blank=True, choices=[('UZS', "So'm"), ('USD', 'US dollar'), ('EUR', 'Euro')], default='', help_text='Currency of the shop price.', max_length=3),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='external_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The shop's own price. Leave empty unless somebody has checked it — the UI then sends the child to the shop for the price instead of inventing one.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Product page at the shop that sells it. Set = a real product, bought with money.'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='merchant',
            field=models.CharField(blank=True, default='', help_text='Name of that shop: Asaxiy, LEGO, Estes Rockets, Uzum Market…', max_length=80),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='item_type',
            field=models.CharField(choices=[('spaceship', 'Spaceship'), ('badge', 'Badge'), ('boost', 'XP Boost'), ('book', 'Book'), ('model_kit', 'Model Kit'), ('apparel', 'Clothing'), ('rocket_module', 'Rocket Module'), ('satellite', 'Satellite'), ('avatar', 'Avatar'), ('theme', 'Theme'), ('tool', 'Tool'), ('other', 'Other')], max_length=20),
        ),
    ]
