# Generated by Django 6.0 on 2026-08-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_adr0001_slug_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclesson',
            name='content_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topiclesson',
            name='content_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='topiclesson',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Lesson text, markdown, in Uzbek. The original — the other two are written from it, and both fall back to it.'),
        ),
    ]
