# Generated by Django 5.2.17 on 2026-08-27 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_mission_usermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usergamificationprofile',
            index=models.Index(fields=['-xp'], name='gamification_xp_desc_idx'),
        ),
    ]
