# Generated by Django 6.0 on 2026-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSatellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('catalog_name', models.CharField(max_length=100)),
                ('norad_id', models.PositiveIntegerField(blank=True, help_text='Leave empty until a catalogue number is actually published. The page joins to the live element feed on this.', null=True, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('mission_type', models.CharField(choices=[('station', 'Crewed station'), ('earth_obs', 'Earth observation'), ('weather', 'Weather'), ('science', 'Science'), ('navigation', 'Navigation'), ('communication', 'Communication')], max_length=20)),
                ('operator', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('launch_site', models.CharField(blank=True, max_length=160)),
                ('launch_vehicle', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False, help_text='Pinned to the top of the Live page list')),
            ],
            options={
                'verbose_name': 'Tracked satellite',
                'ordering': ['-is_featured', 'catalog_name'],
                'indexes': [models.Index(fields=['-is_featured', 'catalog_name'], name='sat_featured_name_idx')],
            },
        ),
    ]
